# Generated by Django 5.2.8 on 2025-11-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('year', models.CharField(max_length=10, verbose_name='Год')),
                ('imdb_id', models.CharField(max_length=20, unique=True, verbose_name='ID фильма')),
                ('poster_url', models.URLField(verbose_name='Ссылка на постер')),
            ],
        ),
    ]
