# Generated by Django 5.2.8 on 2025-12-06 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_favoritemovie_user_alter_favoritemovie_imdb_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritemovie',
            name='imdb_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='favoritemovie',
            name='poster_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='favoritemovie',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='favoritemovie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favoritemovie',
            name='year',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
