# Generated by Django 4.2.11 on 2025-12-17 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0005_profile_movierating'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('poster', models.URLField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('list_type', models.CharField(choices=[('watch_later', 'Посмотрю позже'), ('family', 'Буду смотреть с семьей')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'imdb_id', 'list_type')},
            },
        ),
    ]
